---
hostname: MyRouter2

loopbacks:
  lo0:
    ip: 1.1.1.1
    description: Loopback 0
    ospf_ip: 1.1.1.0
    ospf_area: 1
  lo1:
    ip: 2.2.2.2
    description: Loopback 1
    ospf_ip: 2.2.2.0
    ospf_area: 1
  lo2:
    ip: 3.3.3.3
    description: Loopback 2
  lo3:
    ip: 4.4.4.4
  lo4:
    ip: 5.5.5.5
    description: Loopback 4
  lo5:
    ip: 6.6.6.6
    ospf_ip: 6.6.6.0
    ospf_area: 2
    auth: true


interfaces:
  main:
    ip: 192.168.0.36
    description: Loopback 0
    ospf_area: 0