---
- name: Configure Cisco routers
  hosts: routers
  gather_facts: no

  tasks:
    - name: Show version
      ios_command:
        commands: show version

    - name: Set hostname
      become: true
      ios_config:
        lines:
          - hostname {{ hostname }}

    - name: Set password-encryption
      become: true
      ios_config:
        lines:
          - service password-encryption

    - name: Set system logging to remote server
      become: true
      ios_config:
        lines:
          - logging host {{ item }}
          - logging trap debugging

      loop: "{{ syslog_servers }}"

    - name: Configure NTP servers
      become: true
      ios_config:
        lines:
          - ntp server {{ item }}
      loop: "{{ ntp_servers }}"
