- name: Run basic Cisco router commands
  hosts: routers
  remote_user: test
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Fetch ip command outputs
      cisco.ios.ios_command:
        commands:
          - show ip int br
          - show arp
          - show ip route
      register: output

    - debug: var=output
