---
- name: Lab 04 - Configure Cisco routers with templates
  hosts: routers

  tasks:
    - name: Basic config
      become: true
      ios_config:
        lines:
          - hostname {{ hostname }}
          - service password-encryption
      register: basic_conf_changes

    - name: Configure interfaces
      ios_config:
        src: templates/interfaces.j2
      register: int_config

    - name: Configure ospf
      ios_config:
        src: templates/ospf.j2
      register: ospf_config

    - name: Configure ospf auth
      ios_config:
        src: templates/ospf_auth.j2
      register: ospf_config

    - name: Show OSPF routes
      ios_command:
        commands:
          - show ip route ospf
      register: ospf_routes

    - name: Show OSPF neighbour IDs
      ios_command:
        commands:
          - show ip ospf neighbor
      register: ospf_neighbours

    - name: Show number of learned routes
      debug:
        msg: "Count ospf routes: {{ ospf_routes.stdout[0] | regex_findall('(?:[0-9]{1,3}\\.){3}[0-9]{1,3}[,]') | count }}"

    - name: Parse Neighbours for IDs
      set_fact:
        parse_neighbours: "{{ ospf_neighbours.stdout[0] | regex_findall('[\\n]{1}(?:[0-9]{1,3}\\.){3}[0-9]{1,3}') }}"

    - name: Neighbor IDs
      debug:
        msg: "Neighbour ID: {{ item.replace('\\n', '').replace('\n', '') }}"
      loop: "{{ parse_neighbours }}"

    - name: Show interfaces config changes
      debug:
        var: int_config.updates
      when: int_config.changed

    - name: Show ospf config changes
      debug:
        var: ospf_config.updates
      when: ospf_config.changed
